# Generated by Django 6.0.3 on 2026-04-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Reparto',
                'verbose_name_plural': 'Reparti',
                'db_table': 'reparti',
                'ordering': ['nome'],
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='documento',
            name='reparto',
            field=models.IntegerField(blank=True, db_column='Reparto', help_text='ID del reparto responsabile.', null=True),
        ),
    ]
