# Generated by Django 6.0.3 on 2026-04-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_reparto_alter_documento_reparto"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatoEsterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(db_column="Nome", max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Stato esterno",
                "verbose_name_plural": "Stati esterni",
                "db_table": "stati_esterni",
                "ordering": ["nome"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StatoInterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(db_column="Nome", max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Stato interno",
                "verbose_name_plural": "Stati interni",
                "db_table": "stati_interni",
                "ordering": ["nome"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Revisione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rev_no", models.IntegerField(blank=True, db_column="RevNo", null=True)),
                ("rev_let", models.CharField(blank=True, db_column="RevLet", max_length=10)),
                ("dis_plan_date", models.DateField(blank=True, db_column="DisPlanDate", null=True)),
                ("dis_act_date", models.DateField(blank=True, db_column="DisActDate", null=True)),
                ("rec_plan_date", models.DateField(blank=True, db_column="RecPlanDate", null=True)),
                ("rec_act_date", models.DateField(blank=True, db_column="RecActDate", null=True)),
                (
                    "documento",
                    models.ForeignKey(
                        db_column="IdDoc",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisioni",
                        to="core.documento",
                    ),
                ),
                (
                    "ext_status",
                    models.ForeignKey(
                        blank=True,
                        db_column="ExtStatus",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisioni",
                        to="core.statoesterno",
                    ),
                ),
                (
                    "int_status",
                    models.ForeignKey(
                        blank=True,
                        db_column="IntStatus",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisioni",
                        to="core.statointerno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisione",
                "verbose_name_plural": "Revisioni",
                "db_table": "revisioni",
                "ordering": ["rev_no"],
                "managed": True,
            },
        ),
    ]
