# Generated by Django 6.0.3 on 2026-04-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_statoesterno_statointerno_revisione"),
    ]

    operations = [
        migrations.AddField(
            model_name="statoesterno",
            name="colore",
            field=models.CharField(
                blank=True,
                db_column="Colore",
                default="",
                help_text="Colore esadecimale (es. #00B050).",
                max_length=7,
            ),
        ),
    ]
