# Generated by Django 6.0.3 on 2026-04-13 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_convert_reparto_and_status_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(db_column='Testo', max_length=500)),
                ('letta', models.BooleanField(db_column='Letta', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('destinatario', models.ForeignKey(db_column='Destinatario', on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifica',
                'verbose_name_plural': 'Notifiche',
                'db_table': 'notifiche',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reparto', models.CharField(db_column='Reparto', max_length=100)),
                ('stato', models.CharField(choices=[('da_iniziare', 'Da iniziare'), ('in_lavorazione', 'In lavorazione'), ('in_revisione', 'In revisione'), ('in_approvazione', 'In approvazione'), ('concluso', 'Concluso')], db_column='Stato', default='da_iniziare', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('approvatore', models.ForeignKey(db_column='Approvatore', on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_approvatore', to=settings.AUTH_USER_MODEL)),
                ('esecutore', models.ForeignKey(db_column='Esecutore', on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_esecutore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Ticket',
                'db_table': 'ticket',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TicketNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(db_column='Testo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('autore', models.ForeignKey(db_column='Autore', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_ticket', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota ticket',
                'verbose_name_plural': 'Note ticket',
                'db_table': 'ticket_note',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Reparto',
        ),
        migrations.AlterField(
            model_name='revisione',
            name='int_status',
            field=models.CharField(blank=True, choices=[('da_iniziare', 'Da iniziare'), ('in_lavorazione', 'In lavorazione'), ('in_revisione', 'In revisione'), ('in_approvazione', 'In approvazione'), ('da_emettere', 'Da emettere'), ('inviato_al_cliente', 'Inviato al Cliente'), ('ricevuto', 'Ricevuto')], db_column='IntStatus', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='revisione',
            name='crea_nuova_rev',
            field=models.BooleanField(db_column='CreaNuovaRev', default=False, help_text='Flag per creare una nuova revisione al rientro dal cliente.'),
        ),
        migrations.AddField(
            model_name='revisione',
            name='note_rientro',
            field=models.TextField(blank=True, db_column='NoteRientro', default='', help_text='Note relative al rientro dal cliente.'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='reparto',
            field=models.CharField(blank=True, db_column='Reparto', default='', help_text='Nome del reparto responsabile.', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='revisioni',
            field=models.ManyToManyField(blank=True, db_table='ticket_revisioni', related_name='tickets', to='core.revisione'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='revisore',
            field=models.ForeignKey(db_column='Revisore', on_delete=django.db.models.deletion.RESTRICT, related_name='ticket_revisore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notifica',
            name='ticket',
            field=models.ForeignKey(blank=True, db_column='TicketId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to='core.ticket'),
        ),
        migrations.AddField(
            model_name='ticketnota',
            name='ticket',
            field=models.ForeignKey(db_column='TicketId', on_delete=django.db.models.deletion.CASCADE, related_name='note', to='core.ticket'),
        ),
        migrations.DeleteModel(
            name='StatoInterno',
        ),
    ]
