# Generated by Django 6.0.3 on 2026-04-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reparto_acronimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='stato',
        ),
    ]
