# Generated by Django 6.0.3 on 2026-05-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_statoesterno_options_user_badge_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='badge_color',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, db_column='Avatar', null=True, upload_to='avatars/'),
        ),
    ]
