# Generated by Django 6.0.5 on 2026-05-11 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_remove_user_badge_color_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="creato_da",
            field=models.ForeignKey(
                blank=True,
                db_column="CreatoDA",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_creati",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
