# Generated by Django 6.0.5 on 2026-05-11 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_ticket_creato_da"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="assegnato_da",
            field=models.ForeignKey(
                blank=True,
                db_column="AssegnatoDa",
                help_text="Utente che ha effettuato (o aggiornato) l'assegnazione del ticket.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_assegnati",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
