# Generated by Django 6.0.5 on 2026-05-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_assegnato_da_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="note_assegnazione",
            field=models.TextField(
                blank=True,
                db_column="NoteAssegnazione",
                default="",
                help_text="Note relative all'assegnazione del ticket.",
            ),
        ),
    ]
