# Generated by Django 6.0.5 on 2026-05-11 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_ticket_note_assegnazione"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifica",
            name="mittente",
            field=models.ForeignKey(
                blank=True,
                db_column="Mittente",
                help_text="Utente che ha generato la notifica.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifiche_inviate",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
