# Generated by Django 6.0.5 on 2026-05-11 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_mittente_notifica"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="creato_da",
        ),
    ]
