# Generated by Django 6.0.3 on 2026-05-21 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_update_sent_status_colors"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisioneFileLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "percorso",
                    models.CharField(
                        db_column="Percorso",
                        help_text="Percorso completo al file sul fileserver.",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_column="CreatedAt")),
                ("updated_at", models.DateTimeField(auto_now=True, db_column="UpdatedAt")),
                (
                    "revisione",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_link",
                        to="core.revisione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link file revisione",
                "verbose_name_plural": "Link file revisioni",
                "db_table": "revisioni_file_link",
                "managed": True,
            },
        ),
    ]
