# Generated by Django 6.0.3 on 2026-05-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_add_revisione_file_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stabilimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(db_column="Nome", max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Stabilimento",
                "verbose_name_plural": "Stabilimenti",
                "db_table": "stabilimenti",
                "ordering": ["nome"],
                "managed": True,
            },
        ),
    ]
