# Generated by Django 6.0.5 on 2026-05-26 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_stabilimento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="approvatore",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="assegnato_da",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="esecutore",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="revisioni",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="revisore",
        ),
        migrations.RemoveField(
            model_name="ticketnota",
            name="ticket",
        ),
        migrations.RemoveField(
            model_name="ticketnota",
            name="autore",
        ),
        migrations.RemoveField(
            model_name="revisione",
            name="note_rientro",
        ),
        migrations.DeleteModel(
            name="Notifica",
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
        migrations.DeleteModel(
            name="TicketNota",
        ),
    ]
