# Generated by Django 6.0.4 on 2026-05-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rimuovi_ticket_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='statoesterno',
            name='crea_nuova_rev',
            field=models.BooleanField(db_column='CreaNuovaRev', default=True, help_text='Se attivo, alla ricezione con questa risposta viene creata automaticamente una nuova revisione.', verbose_name='Crea nuova revisione'),
        ),
    ]
