# Generated by Django 6.0.5 on 2026-06-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_cartellamodellodocumento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modellodocumento",
            options={
                "managed": True,
                "ordering": ["doc_title", "pk"],
                "verbose_name": "Modello documento",
                "verbose_name_plural": "Modelli documento",
            },
        ),
        migrations.AddField(
            model_name="testata",
            name="actual_delivery_date",
            field=models.DateField(blank=True, db_column="ActualDeliveryDate", null=True),
        ),
        migrations.AlterField(
            model_name="cartellamodellodocumento",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
