# Generated by Django 6.0.5 on 2026-07-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_revisione_ignora_anomalie"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="contractor_doc_no",
            field=models.CharField(
                blank=True, db_column="ContractorDocNo", default="", max_length=200
            ),
        ),
    ]
