# Generated by Django 6.0.5 on 2026-08-04 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_documento_contractor_doc_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommessaPin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pinned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "testata",
                    models.ForeignKey(
                        db_column="Job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="core.testata",
                        to_field="job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commessa_pins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pin commessa",
                "verbose_name_plural": "Pin commesse",
                "db_table": "commessa_pins",
                "ordering": ["pinned_at"],
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "testata"), name="uniq_user_commessa_pin"
                    )
                ],
            },
        ),
    ]
