# Generated by Django 6.0.3 on 2026-08-31 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_statoesterno_lettera"),
    ]

    operations = [
        migrations.CreateModel(
            name="Segnalazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("feature", "Feature"), ("problema", "Problema")], max_length=20
                    ),
                ),
                ("titolo", models.CharField(max_length=200)),
                ("testo", models.TextField()),
                (
                    "stato",
                    models.CharField(
                        choices=[("aperto", "Aperto"), ("chiuso", "Chiuso")],
                        default="aperto",
                        max_length=20,
                    ),
                ),
                ("chiuso_il", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "autore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segnalazioni",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chiuso_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="segnalazioni_chiuse",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Segnalazione",
                "verbose_name_plural": "Segnalazioni",
                "db_table": "segnalazioni",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SegnalazioneCommento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("testo", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "autore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segnalazione_commenti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "segnalazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commenti",
                        to="core.segnalazione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commento segnalazione",
                "verbose_name_plural": "Commenti segnalazioni",
                "db_table": "segnalazione_commenti",
                "ordering": ["created_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SegnalazioneVoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("valore", models.SmallIntegerField()),
                (
                    "segnalazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voti",
                        to="core.segnalazione",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segnalazione_voti",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto segnalazione",
                "verbose_name_plural": "Voti segnalazioni",
                "db_table": "segnalazione_voti",
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("segnalazione", "utente"), name="uniq_utente_segnalazione_voto"
                    )
                ],
            },
        ),
    ]
