# Generated by Django 6.0.5 on 2026-09-02 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_segnalazione"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transmittal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("numero", models.PositiveIntegerField(db_column="Numero")),
                (
                    "data_emissione",
                    models.DateField(blank=True, db_column="DataEmissione", null=True),
                ),
                (
                    "revisioni",
                    models.ManyToManyField(
                        blank=True,
                        db_table="trasmittal_revisioni",
                        related_name="trasmittal",
                        to="core.revisione",
                    ),
                ),
                (
                    "testata",
                    models.ForeignKey(
                        db_column="Job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trasmittal",
                        to="core.testata",
                        to_field="job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transmittal",
                "verbose_name_plural": "Transmittal",
                "db_table": "trasmittal",
                "ordering": ["-numero"],
                "managed": True,
                "unique_together": {("testata", "numero")},
            },
        ),
    ]
