# Generated by Django 6.0.5 on 2026-09-02 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_transmittal"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stabilimento",
            field=models.ForeignKey(
                blank=True,
                db_column="Stabilimento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utenti",
                to="core.stabilimento",
            ),
        ),
    ]
