# Generated by Django 6.0.5 on 2026-09-04 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_clear_transmittal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("testo", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("letta_il", models.DateTimeField(blank=True, null=True)),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifiche",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "segnalazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifiche",
                        to="core.segnalazione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notifica",
                "verbose_name_plural": "Notifiche",
                "db_table": "notifiche",
                "ordering": ["-created_at", "-id"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["destinatario", "letta_il"], name="idx_notifica_dest_letta"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("destinatario", "segnalazione"),
                        name="uniq_destinatario_segnalazione_notifica",
                    )
                ],
            },
        ),
    ]
