# Generated by Django 6.0.5 on 2026-09-05 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_notifica"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggiornamentoBC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("campo", models.CharField(db_column="Campo", max_length=50)),
                (
                    "valore_precedente",
                    models.CharField(blank=True, db_column="ValorePrecedente", max_length=300),
                ),
                (
                    "valore_nuovo",
                    models.CharField(blank=True, db_column="ValoreNuovo", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "testata",
                    models.ForeignKey(
                        db_column="Job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggiornamenti_bc",
                        to="core.testata",
                        to_field="job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aggiornamento da Business Central",
                "verbose_name_plural": "Aggiornamenti da Business Central",
                "db_table": "aggiornamenti_bc",
                "ordering": ["-created_at", "-id"],
                "managed": True,
                "indexes": [
                    models.Index(fields=["testata", "created_at"], name="idx_agg_bc_testata_data")
                ],
            },
        ),
    ]
