# Generated by Django 6.0.3 on 2026-09-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_aggiornamentobc"),
    ]

    operations = [
        migrations.CreateModel(
            name="EsecuzioneSchedulata",
            fields=[
                ("nome", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("ultima_esecuzione", models.DateTimeField(blank=True, null=True)),
                ("esito", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name": "Esecuzione schedulata",
                "verbose_name_plural": "Esecuzioni schedulate",
                "db_table": "esecuzioni_schedulate",
                "ordering": ["nome"],
                "managed": True,
            },
        ),
    ]
