# Generated by Django 6.0.3 on 2026-09-14 08:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_esecuzioneschedulata"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firma",
            field=models.ImageField(
                blank=True,
                db_column="Firma",
                null=True,
                upload_to="firme/",
                validators=[core.models.valida_immagine_firma],
                verbose_name="Immagine di firma",
            ),
        ),
    ]
