# Generated by Django 6.0.5 on 2026-09-07 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_esecuzioneschedulata"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityControlPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "doc_no",
                    models.CharField(
                        blank=True, db_column="DocNo", max_length=100, verbose_name="Doc n."
                    ),
                ),
                ("location", models.CharField(blank=True, db_column="Location", max_length=200)),
                (
                    "sheet",
                    models.CharField(
                        blank=True, db_column="Sheet", max_length=50, verbose_name="Foglio"
                    ),
                ),
                ("project", models.CharField(blank=True, db_column="Project", max_length=300)),
                (
                    "dwg_no",
                    models.CharField(
                        blank=True, db_column="DwgNo", max_length=100, verbose_name="Dwg n."
                    ),
                ),
                ("owner", models.CharField(blank=True, db_column="Owner", max_length=200)),
                (
                    "po_no",
                    models.CharField(
                        blank=True, db_column="PONo", max_length=100, verbose_name="PO n."
                    ),
                ),
                ("data", models.DateField(blank=True, db_column="Data", null=True)),
                ("purchaser", models.CharField(blank=True, db_column="Purchaser", max_length=200)),
                (
                    "descrizione_item",
                    models.CharField(blank=True, db_column="DescrizioneItem", max_length=300),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, db_column="SerialNo", max_length=100, verbose_name="Serial n."
                    ),
                ),
                (
                    "prepared_by",
                    models.CharField(blank=True, db_column="PreparedBy", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prepared_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_control_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "testata",
                    models.ForeignKey(
                        db_column="Job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_control_plans",
                        to="core.testata",
                        to_field="job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quality Control Plan",
                "verbose_name_plural": "Quality Control Plan",
                "db_table": "quality_control_plan",
                "ordering": ["-created_at", "-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="QualityControlPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "item_no",
                    models.CharField(db_column="ItemNo", max_length=200, verbose_name="Item"),
                ),
                (
                    "descrizione",
                    models.CharField(blank=True, db_column="Descrizione", max_length=300),
                ),
                ("ordine", models.PositiveSmallIntegerField(db_column="Ordine", default=0)),
                (
                    "piano",
                    models.ForeignKey(
                        db_column="IdQCP",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.qualitycontrolplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item del Quality Control Plan",
                "verbose_name_plural": "Item del Quality Control Plan",
                "db_table": "quality_control_plan_items",
                "ordering": ["ordine", "id"],
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="qualitycontrolplan",
            index=models.Index(fields=["testata", "created_at"], name="idx_qcp_testata_data"),
        ),
        migrations.AddConstraint(
            model_name="qualitycontrolplanitem",
            constraint=models.UniqueConstraint(fields=("piano", "item_no"), name="uniq_qcp_item"),
        ),
    ]
