# Generated by Django 6.0.3 on 2026-09-14 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_firma_utente"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonaCommessa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ruolo",
                    models.CharField(
                        choices=[("pm", "PM"), ("pe", "PE"), ("qci", "QCI"), ("we", "WE")],
                        max_length=10,
                    ),
                ),
                ("nome_libero", models.CharField(blank=True, max_length=200)),
                (
                    "testata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persone",
                        to="core.testata",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commesse_persona",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona commessa",
                "verbose_name_plural": "Persone commessa",
                "db_table": "persone_commessa",
                "ordering": ["testata", "ruolo", "id"],
                "managed": True,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("nome_libero", ""), ("utente__isnull", False)),
                            models.Q(
                                ("utente__isnull", True),
                                models.Q(("nome_libero", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="ck_persona_commessa_utente_xor_nome_libero",
                    )
                ],
            },
        ),
    ]
