# Generated by Django 6.0.3 on 2026-09-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_qualitycontrolplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitycontrolplan",
            name="titolo",
            field=models.CharField(blank=True, db_column="Titolo", max_length=200),
        ),
    ]
