# Generated by Django 6.0.3 on 2026-09-14 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_firma_utente"),
    ]

    operations = [
        migrations.AddField(
            model_name="stabilimento",
            name="codice_bc",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_column="CodiceBC",
                null=True,
                unique=True,
                verbose_name="Codice sito Business Central",
            ),
        ),
        migrations.AddField(
            model_name="stabilimento",
            name="sigla",
            field=models.CharField(
                blank=True, db_column="Sigla", max_length=2, null=True, unique=True
            ),
        ),
        migrations.CreateModel(
            name="FirmatarioStabilimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ruolo",
                    models.CharField(
                        choices=[("produzione", "Produzione"), ("qualita", "Qualità")],
                        max_length=20,
                    ),
                ),
                (
                    "stabilimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firmatari",
                        to="core.stabilimento",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="firmatario_di",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Firmatario stabilimento",
                "verbose_name_plural": "Firmatari stabilimento",
                "db_table": "firmatari_stabilimento",
                "ordering": ["stabilimento", "ruolo"],
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stabilimento", "ruolo"), name="uniq_firmatario_stabilimento_ruolo"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IndirizzoStabilimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("tipo", models.CharField(choices=[("to", "A"), ("cc", "CC")], max_length=10)),
                ("attivo", models.BooleanField(default=True)),
                (
                    "stabilimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indirizzi",
                        to="core.stabilimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indirizzo stabilimento",
                "verbose_name_plural": "Indirizzi stabilimento",
                "db_table": "indirizzi_stabilimento",
                "ordering": ["stabilimento", "tipo", "email"],
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stabilimento", "email", "tipo"), name="uniq_indirizzo_stabilimento"
                    )
                ],
            },
        ),
    ]
