# Generated by Django 6.0.3 on 2026-09-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_qualitycontrolplan_titolo"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitycontrolplan",
            name="asme_stamp",
            field=models.BooleanField(
                db_column="AsmeStamp", default=False, verbose_name="ASME stamp"
            ),
        ),
        migrations.AddField(
            model_name="qualitycontrolplan",
            name="dwg_base",
            field=models.CharField(
                blank=True, db_column="DwgBase", max_length=20, verbose_name="Dwg n. (base)"
            ),
        ),
        migrations.AddField(
            model_name="qualitycontrolplan",
            name="foglio_dwg",
            field=models.CharField(
                blank=True, db_column="FoglioDwg", max_length=20, verbose_name="Foglio disegno n."
            ),
        ),
        migrations.AddField(
            model_name="qualitycontrolplan",
            name="h2s_service",
            field=models.BooleanField(
                db_column="H2SService", default=False, verbose_name="H2S service"
            ),
        ),
        migrations.AddField(
            model_name="qualitycontrolplan",
            name="lethal_service",
            field=models.BooleanField(
                db_column="LethalService", default=False, verbose_name="Lethal service"
            ),
        ),
        migrations.AddField(
            model_name="qualitycontrolplan",
            name="mdmt",
            field=models.CharField(
                blank=True, db_column="MDMT", max_length=50, verbose_name="MDMT"
            ),
        ),
        migrations.AddField(
            model_name="qualitycontrolplan",
            name="national_board",
            field=models.BooleanField(
                db_column="NationalBoard", default=False, verbose_name="National Board"
            ),
        ),
        migrations.AddField(
            model_name="qualitycontrolplan",
            name="notification_advice_time",
            field=models.CharField(
                blank=True,
                db_column="NotificationAdviceTime",
                max_length=200,
                verbose_name="Notification advice time",
            ),
        ),
        migrations.AddField(
            model_name="qualitycontrolplan",
            name="rev_no",
            field=models.PositiveSmallIntegerField(
                db_column="RevNo", default=0, verbose_name="Rev n."
            ),
        ),
        migrations.AddField(
            model_name="qualitycontrolplan",
            name="serial_base",
            field=models.CharField(
                blank=True, db_column="SerialBase", max_length=20, verbose_name="Serial n. (base)"
            ),
        ),
        migrations.AlterField(
            model_name="qualitycontrolplan",
            name="doc_no",
            field=models.CharField(
                blank=True,
                db_column="DocNo",
                help_text="Vuoto: si usa il numero calcolato.",
                max_length=100,
                verbose_name="Doc n.",
            ),
        ),
        migrations.AlterField(
            model_name="qualitycontrolplan",
            name="dwg_no",
            field=models.CharField(
                blank=True,
                db_column="DwgNo",
                help_text="Vuoto: si usa il numero calcolato.",
                max_length=100,
                verbose_name="Dwg n.",
            ),
        ),
        migrations.AlterField(
            model_name="qualitycontrolplan",
            name="serial_no",
            field=models.CharField(
                blank=True,
                db_column="SerialNo",
                help_text="Vuoto: si usa il numero calcolato.",
                max_length=100,
                verbose_name="Serial n.",
            ),
        ),
        migrations.AlterField(
            model_name="qualitycontrolplan",
            name="sheet",
            field=models.CharField(
                blank=True, db_column="Sheet", max_length=50, verbose_name="Foglio QCP"
            ),
        ),
    ]
