# Generated by Django 6.0.3 on 2026-09-14 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_popola_sigla_codice_bc_stabilimenti"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinazioneDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinazioni",
                        to="core.documento",
                    ),
                ),
                (
                    "stabilimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documenti_destinati",
                        to="core.stabilimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destinazione documento",
                "verbose_name_plural": "Destinazioni documento",
                "db_table": "destinazioni_documento",
                "ordering": ["documento", "stabilimento"],
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("documento", "stabilimento"), name="uniq_destinazione_documento"
                    )
                ],
            },
        ),
    ]
