# Generated by Django 6.0.5 on 2026-09-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_risposte_cliente_colori_e_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testata",
            name="requisition",
            field=models.CharField(
                blank=True, db_column="Requisition", max_length=300, verbose_name="Bid no."
            ),
        ),
    ]
