# Generated by Django 6.0.3 on 2026-09-10 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_qualitycontrolplan_dati_tecnici"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityControlPlanAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(db_column="Nome", max_length=200, verbose_name="Ente")),
                ("ordine", models.PositiveSmallIntegerField(db_column="Ordine", default=0)),
                (
                    "piano",
                    models.ForeignKey(
                        db_column="IdQCP",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agencies",
                        to="core.qualitycontrolplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ente di ispezione del Quality Control Plan",
                "verbose_name_plural": "Enti di ispezione del Quality Control Plan",
                "db_table": "quality_control_plan_agencies",
                "ordering": ["ordine", "id"],
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(fields=("piano", "nome"), name="uniq_qcp_agency")
                ],
            },
        ),
        migrations.CreateModel(
            name="QualityControlPlanCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codice",
                    models.CharField(db_column="Codice", max_length=200, verbose_name="Codice"),
                ),
                ("ordine", models.PositiveSmallIntegerField(db_column="Ordine", default=0)),
                (
                    "piano",
                    models.ForeignKey(
                        db_column="IdQCP",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="core.qualitycontrolplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Codice applicabile del Quality Control Plan",
                "verbose_name_plural": "Codici applicabili del Quality Control Plan",
                "db_table": "quality_control_plan_codes",
                "ordering": ["ordine", "id"],
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(fields=("piano", "codice"), name="uniq_qcp_code")
                ],
            },
        ),
        migrations.CreateModel(
            name="QualityControlPlanSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("spec", models.CharField(db_column="Spec", max_length=300, verbose_name="Spec")),
                ("ordine", models.PositiveSmallIntegerField(db_column="Ordine", default=0)),
                (
                    "piano",
                    models.ForeignKey(
                        db_column="IdQCP",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="core.qualitycontrolplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Specifica cliente del Quality Control Plan",
                "verbose_name_plural": "Specifiche cliente del Quality Control Plan",
                "db_table": "quality_control_plan_specs",
                "ordering": ["ordine", "id"],
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(fields=("piano", "spec"), name="uniq_qcp_spec")
                ],
            },
        ),
    ]
