# Generated by Django 6.0.3 on 2026-09-14 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_destinazione_documento"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransmittalInterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("data", models.DateField()),
                ("progressivo", models.PositiveSmallIntegerField()),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                (
                    "creato_da",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trasmittal_interni_creati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "testata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trasmittal_interni",
                        to="core.testata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trasmittal interno",
                "verbose_name_plural": "Trasmittal interni",
                "db_table": "trasmittal_interni",
                "ordering": ["-data", "-progressivo"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RigaTransmittalInterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revisione", models.CharField(max_length=10)),
                ("copie", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("tpi", models.CharField(blank=True, max_length=50)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("cliente", models.BooleanField(default=True)),
                (
                    "posizione",
                    models.PositiveSmallIntegerField(help_text="Ordine di stampa nella lettera."),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="righe_trasmittal_interno",
                        to="core.documento",
                    ),
                ),
                (
                    "siti",
                    models.ManyToManyField(
                        blank=True,
                        db_table="riga_trasmittal_interno_siti",
                        related_name="righe_trasmittal_interno",
                        to="core.stabilimento",
                    ),
                ),
                (
                    "trasmittal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="righe",
                        to="core.transmittalinterno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riga trasmittal interno",
                "verbose_name_plural": "Righe trasmittal interno",
                "db_table": "righe_trasmittal_interno",
                "ordering": ["trasmittal", "posizione"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DestinatarioTransmittalInterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("tipo", models.CharField(choices=[("to", "A"), ("cc", "CC")], max_length=10)),
                (
                    "origine",
                    models.CharField(
                        choices=[
                            ("stabilimento", "Stabilimento"),
                            ("pm", "PM"),
                            ("pe", "PE"),
                            ("qci", "QCI"),
                            ("export", "Export"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trasmittal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinatari",
                        to="core.transmittalinterno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destinatario trasmittal interno",
                "verbose_name_plural": "Destinatari trasmittal interno",
                "db_table": "destinatari_trasmittal_interno",
                "ordering": ["trasmittal", "tipo", "email"],
                "managed": True,
            },
        ),
        migrations.AddConstraint(
            model_name="transmittalinterno",
            constraint=models.UniqueConstraint(
                fields=("testata", "data", "progressivo"),
                name="uniq_trasmittal_interno_progressivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="rigatransmittalinterno",
            constraint=models.UniqueConstraint(
                fields=("trasmittal", "documento"), name="uniq_riga_trasmittal_interno_documento"
            ),
        ),
        migrations.AddConstraint(
            model_name="destinatariotransmittalinterno",
            constraint=models.UniqueConstraint(
                fields=("trasmittal", "email"), name="uniq_destinatario_trasmittal_interno"
            ),
        ),
    ]
