# Generated by Django 6.0.3 on 2026-09-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_qualitycontrolplan_liste"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttivitaQCP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codice",
                    models.CharField(db_column="Codice", max_length=200, verbose_name="Codice"),
                ),
                (
                    "divisione",
                    models.CharField(
                        db_column="Divisione", max_length=20, verbose_name="Divisione"
                    ),
                ),
                (
                    "capitolo",
                    models.CharField(db_column="Capitolo", max_length=100, verbose_name="Capitolo"),
                ),
                (
                    "descrizione",
                    models.CharField(
                        db_column="Descrizione", max_length=300, verbose_name="Descrizione"
                    ),
                ),
                (
                    "test_inspection",
                    models.CharField(
                        blank=True,
                        db_column="TestInspection",
                        max_length=200,
                        verbose_name="Test / inspection",
                    ),
                ),
                (
                    "reference_doc_tipo",
                    models.CharField(
                        choices=[
                            ("suffisso_job", "Job + suffisso"),
                            ("statico", "Statico"),
                            ("composito", "Composito"),
                            ("campo_piano", "Campo del piano"),
                            ("da_proc", "Da matrice saldature"),
                        ],
                        db_column="ReferenceDocTipo",
                        help_text="Come si costruisce il riferimento B&R per una commessa.",
                        max_length=20,
                        verbose_name="Tipo di riferimento",
                    ),
                ),
                (
                    "reference_doc_valore",
                    models.CharField(
                        blank=True,
                        db_column="ReferenceDocValore",
                        help_text='Suffisso del job ("/PT"), testo fisso, parti separate da "|", nome di un campo del piano (dwg_no, doc_no) secondo il tipo.',
                        max_length=200,
                        verbose_name="Riferimento",
                    ),
                ),
                (
                    "acceptance_criteria",
                    models.CharField(
                        blank=True,
                        db_column="AcceptanceCriteria",
                        max_length=300,
                        verbose_name="Acceptance criteria",
                    ),
                ),
                (
                    "documento_richiesto",
                    models.CharField(
                        blank=True,
                        db_column="DocumentoRichiesto",
                        max_length=200,
                        verbose_name="Documento richiesto",
                    ),
                ),
                (
                    "tecnica",
                    models.CharField(
                        blank=True, db_column="Tecnica", max_length=50, verbose_name="Tecnica"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True, db_column="Tipo", max_length=20, verbose_name="Tipo"
                    ),
                ),
                (
                    "ordine",
                    models.PositiveSmallIntegerField(db_column="Ordine", verbose_name="Ordine"),
                ),
                (
                    "attivo",
                    models.BooleanField(db_column="Attivo", default=True, verbose_name="Attiva"),
                ),
            ],
            options={
                "verbose_name": "Attività del catalogo QCP",
                "verbose_name_plural": "Catalogo attività QCP",
                "db_table": "attivita_qcp",
                "ordering": ["ordine", "id"],
                "managed": True,
                "indexes": [
                    models.Index(fields=["capitolo"], name="idx_attivita_qcp_capitolo"),
                    models.Index(fields=["divisione"], name="idx_attivita_qcp_divisione"),
                    models.Index(fields=["tipo"], name="idx_attivita_qcp_tipo"),
                    models.Index(fields=["descrizione"], name="idx_attivita_qcp_descrizione"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("codice", "capitolo"), name="uniq_attivita_qcp_cod_cap"
                    )
                ],
            },
        ),
    ]
