# Generated by Django 6.0.3 on 2026-09-10 13:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_attivitaqcp"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityControlPlanSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "titolo",
                    models.CharField(db_column="Titolo", max_length=200, verbose_name="Titolo"),
                ),
                ("ordine", models.PositiveSmallIntegerField(db_column="Ordine", default=0)),
                (
                    "piano",
                    models.ForeignKey(
                        db_column="IdQCP",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.qualitycontrolplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sezione del Quality Control Plan",
                "verbose_name_plural": "Sezioni del Quality Control Plan",
                "db_table": "quality_control_plan_sections",
                "ordering": ["ordine", "id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="QualityControlPlanStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ordine", models.PositiveSmallIntegerField(db_column="Ordine", default=0)),
                (
                    "descrizione",
                    models.CharField(
                        db_column="Descrizione", max_length=300, verbose_name="Descrizione"
                    ),
                ),
                (
                    "test_inspection",
                    models.CharField(
                        blank=True,
                        db_column="TestInspection",
                        max_length=200,
                        verbose_name="Test / inspection",
                    ),
                ),
                (
                    "reference_doc",
                    models.CharField(
                        blank=True,
                        db_column="ReferenceDoc",
                        max_length=200,
                        verbose_name="Reference doc.",
                    ),
                ),
                (
                    "acceptance_criteria",
                    models.CharField(
                        blank=True,
                        db_column="AcceptanceCriteria",
                        max_length=300,
                        verbose_name="Acceptance criteria",
                    ),
                ),
                (
                    "documento_richiesto",
                    models.CharField(
                        blank=True,
                        db_column="DocumentoRichiesto",
                        max_length=200,
                        verbose_name="Documento richiesto",
                    ),
                ),
                (
                    "tecnica",
                    models.CharField(
                        blank=True, db_column="Tecnica", max_length=50, verbose_name="Tecnica"
                    ),
                ),
                (
                    "report_no",
                    models.CharField(
                        blank=True, db_column="ReportNo", max_length=100, verbose_name="Report n."
                    ),
                ),
                (
                    "extent",
                    models.DecimalField(
                        db_column="Extent",
                        decimal_places=3,
                        default=1,
                        help_text="Frazione fra 0 e 1: 0.1 vuol dire 10%.",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Extent",
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, db_column="Remarks", max_length=300, verbose_name="Remarks"
                    ),
                ),
                (
                    "attivita",
                    models.ForeignKey(
                        blank=True,
                        db_column="IdAttivita",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="steps",
                        to="core.attivitaqcp",
                        verbose_name="Attività di catalogo",
                    ),
                ),
                (
                    "sezione",
                    models.ForeignKey(
                        db_column="IdSezione",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.qualitycontrolplansection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Step del Quality Control Plan",
                "verbose_name_plural": "Step del Quality Control Plan",
                "db_table": "quality_control_plan_steps",
                "ordering": ["ordine", "id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="QualityControlPlanInterventionPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "punto",
                    models.CharField(
                        choices=[
                            ("W", "Witness point"),
                            ("H", "Hold point"),
                            ("R", "Review"),
                            ("SW", "Spot witness"),
                            ("M", "Monitoring"),
                            ("A", "Approval"),
                            ("F", "First of a kind"),
                            ("-", "Non coinvolto"),
                        ],
                        db_column="Punto",
                        default="-",
                        max_length=4,
                        verbose_name="Punto d'intervento",
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        db_column="IdEnte",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punti",
                        to="core.qualitycontrolplanagency",
                        verbose_name="Ente",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        db_column="IdStep",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punti",
                        to="core.qualitycontrolplanstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Punto d'intervento",
                "verbose_name_plural": "Punti d'intervento",
                "db_table": "quality_control_plan_intervention_points",
                "ordering": ["agency__ordine", "agency_id"],
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("step", "agency"), name="uniq_qcp_punto_step_ente"
                    )
                ],
            },
        ),
    ]
