# Generated by Django 6.0.3 on 2026-09-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_qualitycontrolplan_corpo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualitycontrolplaninterventionpoint",
            name="punto",
            field=models.CharField(
                db_column="Punto", default="-", max_length=20, verbose_name="Punto d'intervento"
            ),
        ),
    ]
