# Generated by Django 6.0.3 on 2026-09-15 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_persona_commessa"),
    ]

    operations = [
        migrations.AddField(
            model_name="testata",
            name="sito_costruttivo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commesse_costruttive",
                to="core.stabilimento",
                verbose_name="Sito costruttivo",
            ),
        ),
    ]
