# Generated by Django 6.0.3 on 2026-09-11 11:06

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_qualitycontrolplan_punti_multipli"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firma",
            field=models.ImageField(
                blank=True,
                db_column="Firma",
                null=True,
                upload_to="firme/",
                validators=[core.models.valida_immagine_firma],
                verbose_name="Immagine di firma",
            ),
        ),
        migrations.CreateModel(
            name="QualityControlPlanSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("firmato_il", models.DateTimeField(auto_now_add=True, db_column="FirmatoIl")),
                (
                    "esito",
                    models.CharField(
                        choices=[
                            ("conforme", "Conforme"),
                            ("non_conforme", "Non conforme"),
                            ("non_applicabile", "Non applicabile"),
                        ],
                        db_column="Esito",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, db_column="Note")),
                (
                    "annullata_il",
                    models.DateTimeField(blank=True, db_column="AnnullataIl", null=True),
                ),
                ("motivo_annullo", models.TextField(blank=True, db_column="MotivoAnnullo")),
                (
                    "annullata_da",
                    models.ForeignKey(
                        blank=True,
                        db_column="AnnullataDa",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="firme_qcp_annullate",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Annullata da",
                    ),
                ),
                (
                    "punto",
                    models.ForeignKey(
                        db_column="IdPunto",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="firme",
                        to="core.qualitycontrolplaninterventionpoint",
                        verbose_name="Punto d'intervento",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        db_column="IdUtente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="firme_qcp",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Firmata da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma del Quality Control Plan",
                "verbose_name_plural": "Firme del Quality Control Plan",
                "db_table": "quality_control_plan_signatures",
                "ordering": ["firmato_il", "id"],
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("annullata_il__isnull", True)),
                        fields=("punto",),
                        name="uniq_qcp_firma_valida",
                    )
                ],
            },
        ),
    ]
