# Generated by Django 6.0.3 on 2026-09-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_testata_sito_costruttivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destinatariotransmittalinterno",
            name="origine",
            field=models.CharField(
                choices=[
                    ("stabilimento", "Stabilimento"),
                    ("pm", "PM"),
                    ("pe", "PE"),
                    ("qci", "QCI"),
                    ("export", "Export"),
                    ("manuale", "Manuale"),
                ],
                max_length=20,
            ),
        ),
    ]
