# Generated by Django 6.0.3 on 2026-09-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_firme_qcp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualitycontrolplansignature",
            name="esito",
            field=models.CharField(
                choices=[
                    ("conforme", "Conforming"),
                    ("non_conforme", "Non-conforming"),
                    ("non_applicabile", "Not applicable"),
                ],
                db_column="Esito",
                max_length=20,
            ),
        ),
    ]
