# Generated by Django 6.0.3 on 2026-09-24 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_risposte_cliente_colori_e_flag"),
        ("core", "0051_riga_trasmittal_interno_tpi_strutturato"),
    ]

    operations = []
