# Generated by Django 6.0.5 on 2026-09-28 11:16

from django.db import migrations, models


def imposta_scrittori_iniziali(apps, schema_editor):
    """Preserva chi poteva già scrivere sul trasmittal interno (era in codice)."""
    User = apps.get_model("core", "User")
    User.objects.filter(username="mcielok").update(trasmittal_interno_writer=True)


def svuota_scrittori_iniziali(apps, schema_editor):
    """Reversibile senza ripristinare lo stato precedente (era nel codice, non nel DB)."""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_alter_testata_requisition"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="trasmittal_interno_writer",
            field=models.BooleanField(
                db_column="TrasmittalInternoWriter",
                default=False,
                help_text=(
                    "Indipendente dal permesso generale: chi non è spuntato qui vede il "
                    "trasmittal interno ma non può modificarlo (destinazioni, emissione, "
                    "annullo, retry)."
                ),
                verbose_name="Può scrivere sul trasmittal interno",
            ),
        ),
        migrations.RunPython(imposta_scrittori_iniziali, svuota_scrittori_iniziali),
    ]
