# Generated by Django 6.0.3 on 2026-10-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_user_trasmittal_interno_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="testata",
            name="rev_sequenza",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Sequenza revisioni personalizzata"
            ),
        ),
    ]
