# Generated by Django 6.0.5 on 2026-10-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_testata_rev_sequenza"),
    ]

    operations = [
        migrations.AddField(
            model_name="transmittalinterno",
            name="messaggio_email",
            field=models.TextField(blank=True, verbose_name="Messaggio dell'email"),
        ),
    ]
