# Generated by Django 6.0.5 on 2026-10-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_trasmittal_interno_messaggio_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destinatariotransmittalinterno",
            name="origine",
            field=models.CharField(
                choices=[
                    ("stabilimento", "Stabilimento"),
                    ("pm", "PM"),
                    ("pe", "PE"),
                    ("qci", "QCI"),
                    ("export", "Export"),
                    ("default", "Default"),
                    ("manuale", "Manuale"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="IndirizzoDefaultTrasmittalInterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("tipo", models.CharField(choices=[("to", "A"), ("cc", "CC")], max_length=10)),
                ("attivo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Indirizzo default trasmittal interno",
                "verbose_name_plural": "Indirizzi default trasmittal interno",
                "db_table": "indirizzi_default_trasmittal_interno",
                "ordering": ["tipo", "email"],
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email", "tipo"), name="uniq_indirizzo_default_trasmittal_interno"
                    )
                ],
            },
        ),
    ]
