# Generated by Django 6.0.5 on 2026-10-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_alter_destinatariotransmittalinterno_origine_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indirizzodefaulttrasmittalinterno",
            options={
                "managed": True,
                "ordering": ["stabilimento", "tipo", "email"],
                "verbose_name": "Indirizzo default trasmittal interno",
                "verbose_name_plural": "Indirizzi default trasmittal interno",
            },
        ),
        migrations.RemoveConstraint(
            model_name="indirizzodefaulttrasmittalinterno",
            name="uniq_indirizzo_default_trasmittal_interno",
        ),
        migrations.AddField(
            model_name="indirizzodefaulttrasmittalinterno",
            name="stabilimento",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indirizzi_default_trasmittal",
                to="core.stabilimento",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="indirizzodefaulttrasmittalinterno",
            constraint=models.UniqueConstraint(
                fields=("stabilimento", "email", "tipo"),
                name="uniq_indirizzo_default_trasmittal_interno",
            ),
        ),
    ]
